SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS d
JOIN SKILLCODES s1 ON s1.CODE & d.SKILL_CODE = s1.CODE
JOIN SKILLCODES s2 ON s2.CODE & d.SKILL_CODE = s2.CODE
WHERE (s1.NAME = 'Python' OR s1.NAME = 'C#')
GROUP BY d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
ORDER BY d.ID;