SELECT ICECREAM_INFO.FLAVOR
FROM ICECREAM_INFO JOIN FIRST_HALF USING (FLAVOR)
WHERE FIRST_HALF.TOTAL_ORDER > 3000 AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY FIRST_HALF.TOTAL_ORDER DESC;